### ISSUE TITLE
interleaving laser

### ISSUE THREAD

**Issue by vero-npm** [neurophotometrics/neurophotometrics#10]
We have a group actively working with V2 now (635 nm laser stim and photometry). One feature we've been wanting to add is the ability to interleave laser stim with the photometry data.

To do this, we would probably want to increase the dead time to the pulse width of the laser (with some safety buffers added). Photometry frame rate and stim frequency would also have to be coordinated.

For example, though, if we were to record at 50hz and stimulate with a 5ms pulse width:

LED1 on
laser on
wait 5 ms
laser off
trigger camera (exposure 15ms)
LED1 off LED2 on laser on
wait 5 ms
laser off

Safety buffer doesn't have to be long. If I remember correctly, the laser takes <50uS to turn off.

The user could trigger stimulation-- and the system would turn on the laser in the appropriate part of the cycle -- which would likely be slightly off from when they triggered it.

**Comment by vero-npm** [comment]
also needed (and somewhat relevant) - keeping the laser on constant mode (CW) but capping it at 50% max power

**Comment by glopesdev** [comment]
For constant mode, we will probably add a new operator for switching the laser on that includes the laser power capped at 50%.

**Comment by glopesdev** [comment]
Due to limitations of the physical laser, it is complicated to know the maximum interleaved frequency that is allowed through the fiber. This is under investigation but is currently not fixed with the above code.
