### ISSUE TITLE
change FLAGs in bonsai

### ISSUE THREAD

**Issue by vero-npm** [neurophotometrics/neurophotometrics#11]
right now, Flags are: 
Frame Flag 17 and 49 indicate that the 415 is on.
Frame Flag 18 and 50 indicate that the 470 is on.
Frame Flag 20 and 52 indicate that the 560 is on.
49, 50, and 52 indicate that the laser was on during these frames.
*always ignore first frame

would be helpful to have flags with more intuitive meaning - like "15" = 415, and "70" = 470 etc, or something of the sort

**Comment by glopesdev** [comment]
The numbers are actually bit fields in a mask that comes with the camera frame metadata as in V1.

Multiple flags can be active in the same frame (e.g. 415 | 470 | Input0), which will be represented as a bitwise OR of individual bit fields. For this to work properly the numbers assigned to each flag have to be strictly powers of two, ideally consecutive so we don't waste more bits than the ones which are absolutely necessary.

We can keep this open maybe to discuss if there would be other ways to represent multiple bit fields in the text CSV format, maybe as a vertical bar separated list, but this would actually make the file itself harder to parse. We can spread out all possible combinations over different columns, but we would then be creating at least 9 different columns which would be unused the vast majority of the time.
