### ISSUE TITLE
Allow controlling the LED trigger sequence externally

### ISSUE THREAD

**Issue by glopesdev** [neurophotometrics/neurophotometrics#2]
Allow photometry data acquisition to start only on a rising edge of the external DIO line. In this case we might want to avoid LEDs from triggering at all before the line goes up, so the acquisition system should connect without starting the trigger sequence at all.

**Comment by glopesdev** [comment]
A more flexible approach might be to allow starting/stopping the trigger sequence by external commands to the board, and allow starting the board with the trigger sequence off. That way a number of patterns would be allowed including starting on certain events, stopping on certain events, or pausing/resuming.

This requires expanding the public interface of the FP3002 (i.e. more options and input types) so I'll mark it for the next minor release (0.3.0).

**Comment by vero-npm** [comment]
also, allow controlling of camera via TTL in
and/or 
allow controlling of laser via TTL in

**Comment by glopesdev** [comment]
This should be allowed via the command interface proposed above. Any Bonsai event (including TTLs from the FP3002 board) will be able to be used to change the acquisition / stimulation state.
